---
- name: Setup Docker and Docker Compose
  hosts: all
  become: true
  gather_facts: false
  roles:
    - common

#- name: Deploy Logging Services
#  hosts: all
#  become: true
##      gather_facts: false
#  roles:
#    - logging

- name: Build Image and Run db container
  hosts: all
  become: true
  gather_facts: false
  roles:
    - db

- name: Build Image and Run flask container
  hosts: all
  become: true
  gather_facts: false
  roles:
    - api

- name: Build Image and Run webserver container
  hosts: all
  become: true
  gather_facts: false
  roles:
    - web

- name: Build Image and Run nginx load balance container
  hosts: all
  become: true
  gather_facts: false
  roles:
    - lb

#- name: Deploy Monitoring Services
#  hosts: all
#  become: true
#  roles:
#    - monitor

