- name: Build Nginx Image
  docker_image:
    name: "{{ nginx_image }}"
    source: build
    build:
      path: roles/web/files 

- name: Start Nginx1 Container
  become: true
  docker_container:
    name: "{{ nginx1_container_name }}"
    image: "{{ nginx_image }}"
    restart_policy: unless-stopped
    env:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "{{ port_1 }}:{{ port_1 }}"
    volumes:
      - "{{ nginx1_volumes }}"
    networks:
      - name: frontend

- name: Start Nginx2 Container
  become: true
  docker_container:
    name: "{{ nginx2_container_name }}"
    image: "{{ nginx_image }}"
    restart_policy: unless-stopped
    env:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "{{ port_nginx2_1 }}:{{ port_1 }}"
    volumes:
      - "{{ nginx2_volumes }}"
    networks:
      - name: frontend
